# Generated by Django 3.2.7 on 2021-12-03 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('username', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('ans1', models.CharField(blank=True, max_length=100)),
                ('ans2', models.TextField(blank=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
